import { Award, CalendarDays, MapPin, Medal, Pencil, Share2, Shield, Sparkles, Trophy } from 'lucide-react'
import { Avatar, Badge, Button, Card } from '../components/ui'
import { currentProfile, peladas } from '../data/demo'

export function ProfilePage() {
  return <div className="page profile-page">
    <Card className="profile-hero"><div className="profile-cover"><span>GLOBAL PLAYER PROFILE</span></div><div className="profile-main"><Avatar name={currentProfile.name} size="lg"/><div><div className="profile-name"><h1>{currentProfile.name}</h1><Badge tone="lime">VERIFICADO</Badge></div><p>@{currentProfile.username} · <MapPin/> {currentProfile.city}, {currentProfile.country}</p><span className="position-pill">DEFESA · MÉDIO</span></div><div className="profile-actions"><Button variant="outline"><Share2/> Partilhar</Button><Button><Pencil/> Editar perfil</Button></div></div><p className="profile-bio">Organizador da Pelada Browns. Defesa quando é preciso, médio quando deixam. Futebol, produto e uma resenha depois do jogo.</p></Card>
    <div className="profile-stat-grid"><Card><strong>{currentProfile.matches}</strong><span>jogos</span></Card><Card><strong>{currentProfile.goals}</strong><span>gols</span></Card><Card><strong>{currentProfile.assists}</strong><span>assistências</span></Card><Card><strong>{currentProfile.overall}</strong><span>overall global</span></Card></div>
    <div className="profile-columns"><section><div className="section-title-row"><div><span className="eyebrow dark-text">COMUNIDADES</span><h2>Peladas</h2></div></div>{peladas.map((pelada) => <Card className="profile-pelada" key={pelada.id}><span className="pelada-monogram" style={{ background: pelada.accent }}>{pelada.name.split(' ').map((part) => part[0]).slice(0,2).join('')}</span><div><strong>{pelada.name}</strong><small>{pelada.role} · {pelada.members} jogadores</small></div><b>{pelada.role === 'owner' ? <Shield/> : <CalendarDays/>}</b></Card>)}</section><section><div className="section-title-row"><div><span className="eyebrow dark-text">CONQUISTAS</span><h2>Destaques</h2></div></div><div className="achievement-grid"><Card><span className="achievement gold"><Trophy/></span><strong>Craque × 12</strong><small>Top 8% global</small></Card><Card><span className="achievement violet"><Sparkles/></span><strong>Arquiteto</strong><small>50 assistências</small></Card><Card><span className="achievement blue"><Medal/></span><strong>Veterano</strong><small>75 jogos</small></Card><Card><span className="achievement orange"><Award/></span><strong>Fair play</strong><small>Época 25/26</small></Card></div></section></div>
  </div>
}
