import { Award, CalendarDays, MapPin, Medal, Pencil, Share2, Shield, Sparkles, Trophy } from 'lucide-react'
import { Avatar, Badge, Button, Card } from '../components/ui'
import { currentProfile, peladas } from '../data/demo'
import { useI18n } from '../lib/i18n'
import { roleLabel } from '../lib/role-label'

export function ProfilePage() {
  const { t, formatNumber } = useI18n()
  return <div className="page profile-page">
    <Card className="profile-hero"><div className="profile-cover"><span>{t('profile.coverLabel')}</span></div><div className="profile-main"><Avatar name={currentProfile.name} size="lg"/><div><div className="profile-name"><h1>{currentProfile.name}</h1><Badge tone="lime">{t('profile.verified')}</Badge></div><p>@{currentProfile.username} · <MapPin/> {currentProfile.city}, {currentProfile.country}</p><span className="position-pill">{t('profile.positions')}</span></div><div className="profile-actions"><Button variant="outline"><Share2/> {t('profile.share')}</Button><Button><Pencil/> {t('profile.edit')}</Button></div></div><p className="profile-bio">{t('profile.bio')}</p></Card>
    <div className="profile-stat-grid"><Card><strong>{formatNumber(currentProfile.matches)}</strong><span>{t('profile.matches')}</span></Card><Card><strong>{formatNumber(currentProfile.goals)}</strong><span>{t('profile.goals')}</span></Card><Card><strong>{formatNumber(currentProfile.assists)}</strong><span>{t('profile.assists')}</span></Card><Card><strong>{formatNumber(currentProfile.overall, { minimumFractionDigits: 1 })}</strong><span>{t('profile.overall')}</span></Card></div>
    <div className="profile-columns"><section><div className="section-title-row"><div><span className="eyebrow dark-text">{t('profile.communitiesEyebrow')}</span><h2>{t('profile.communitiesTitle')}</h2></div></div>{peladas.map((pelada) => <Card className="profile-pelada" key={pelada.id}><span className="pelada-monogram" style={{ background: pelada.accent }}>{pelada.name.split(' ').map((part) => part[0]).slice(0,2).join('')}</span><div><strong>{pelada.name}</strong><small>{roleLabel(pelada.role, t)} · {t('dashboard.membersCount', { count: pelada.members })}</small></div><b>{pelada.role === 'owner' ? <Shield/> : <CalendarDays/>}</b></Card>)}</section><section><div className="section-title-row"><div><span className="eyebrow dark-text">{t('profile.achievementsEyebrow')}</span><h2>{t('profile.achievementsTitle')}</h2></div></div><div className="achievement-grid"><Card><span className="achievement gold"><Trophy/></span><strong>{t('profile.starTitle', { count: 12 })}</strong><small>{t('profile.starBody', { percent: formatNumber(.08, { style: 'percent' }) })}</small></Card><Card><span className="achievement violet"><Sparkles/></span><strong>{t('profile.architectTitle')}</strong><small>{t('profile.architectBody', { count: 50 })}</small></Card><Card><span className="achievement blue"><Medal/></span><strong>{t('profile.veteranTitle')}</strong><small>{t('profile.veteranBody', { count: 75 })}</small></Card><Card><span className="achievement orange"><Award/></span><strong>{t('profile.fairPlayTitle')}</strong><small>{t('profile.fairPlayBody', { season: '25/26' })}</small></Card></div></section></div>
  </div>
}
